"""
Pydantic schemas for request/response validation.

Zero-knowledge rule: no schema ever exposes raw source code,
file content, or personally identifiable information from GitHub.
"""

from pydantic import BaseModel, Field, field_validator

# ── OAuth ─────────────────────────────────────────────────────────────────────


class AuthorizeResponse(BaseModel):
    """Returned by GET /oauth/github/authorize – tells the caller where to redirect."""

    authorization_url: str = Field(..., description="Full Auth0 authorization URL to redirect the user to")
    state: str = Field(..., description="CSRF-prevention state token; must be validated on callback")


class CallbackRequest(BaseModel):
    """Query parameters forwarded by Auth0 after the user grants access."""

    code: str = Field(..., description="One-time authorization code from Auth0")
    state: str = Field(..., description="State token echoed back by Auth0")


class TokenResponse(BaseModel):
    """Opaque tokens returned to the frontend after a successful OAuth exchange."""

    access_token: str
    token_type: str = "Bearer"
    expires_in: int
    # Refresh token is optional – Auth0 only issues one when offline_access scope is requested
    refresh_token: str | None = None


# ── Agent / Analysis ──────────────────────────────────────────────────────────


class RepoSummary(BaseModel):
    """
    Non-identifying summary of a single repository.
    Raw file content, commit messages, and email addresses are NEVER included.
    """

    name: str
    primary_language: str | None
    languages: dict[str, int] = Field(
        default_factory=dict,
        description="Map of language → bytes of code (from GitHub Linguist)",
    )
    topic_tags: list[str] = Field(default_factory=list)
    is_private: bool
    star_count: int
    fork_count: int


class SkillReport(BaseModel):
    """Structured skill assessment produced by the AI agent."""

    github_username: str
    total_repos_analyzed: int
    detected_skills: list[str] = Field(
        description="Plain-text skill labels, e.g. ['Python: advanced', 'Docker', 'REST API design']"
    )
    top_languages: list[str]
    architecture_patterns: list[str] = Field(
        description="Inferred patterns such as 'microservices', 'event-driven', 'monolith'"
    )
    repo_summaries: list[RepoSummary]
    raw_code_included: bool = Field(
        default=False,
        description="Always False – raw source code is never returned to callers",
    )


# ── Verify request ───────────────────────────────────────────────────────────


class RepoInfo(BaseModel):
    """Basic repo info returned by GET /agent/repos for the configure step."""

    name: str
    top_language: str
    languages: list[str]
    commit_count_90d: int
    repo_size_kb: int
    is_org: bool


class VerifyRequest(BaseModel):
    """Optional configuration for POST /agent/verify."""

    excluded_languages: list[str] = Field(default_factory=list)
    excluded_repos: list[str] = Field(default_factory=list)


# ── AI Verification Report ────────────────────────────────────────────────────


class VerificationReport(BaseModel):
    """
    Zero-knowledge skill verification report generated by the AI agent.

    Produced by analyzing repository metadata (no source code) through Gemini.
    This is the primary output of POST /agent/verify.
    """

    skill_level: str = Field(
        description="Inferred seniority: 'Junior' | 'Mid-Level' | 'Senior' | 'Principal'",
    )
    top_language: str = Field(
        description="Most-used language by byte volume across the analyzed repos",
    )
    security_score: int = Field(
        ge=0,
        le=100,
        description="0–100 maintenance hygiene score (commit regularity, CI presence, issue responsiveness)",
    )
    confidence: str = Field(
        description="Data confidence: 'Low' | 'Medium' | 'High'",
    )
    languages_detected: list[str] = Field(
        default_factory=list,
        description="All languages found across analyzed repos, ordered by total byte volume",
    )
    commit_frequency: str = Field(
        description="Human-readable average commit frequency, e.g. '28 commits/month'",
    )
    complexity_rating: str = Field(
        description="Estimated codebase complexity: 'Low' | 'Medium' | 'High' | 'Very High'",
    )
    repos_analyzed: list[str] = Field(
        default_factory=list,
        description="Names of the repositories that were analyzed (no URLs, no owner info)",
    )
    reasoning: str = Field(
        description="2–4 sentence explanation of how skill_level and security_score were determined",
    )
    generated_at: str = Field(
        description="ISO 8601 UTC timestamp of report generation",
    )

    @field_validator("skill_level", mode="before")
    @classmethod
    def validate_skill_level(cls, v: str) -> str:
        allowed = ["Junior", "Mid-Level", "Senior", "Principal"]
        # Normalize common Gemini variants: "mid level", "mid-level", "midlevel"
        normalized = v.strip().title().replace(" ", "-")
        for option in allowed:
            if option.lower() == v.strip().lower() or option.lower() == normalized.lower():
                return option
        # Fallback: return closest match rather than raising
        v_lower = v.strip().lower()
        if "junior" in v_lower:
            return "Junior"
        if "senior" in v_lower:
            return "Senior"
        if "principal" in v_lower or "lead" in v_lower or "staff" in v_lower:
            return "Principal"
        if "mid" in v_lower:
            return "Mid-Level"
        raise ValueError(f"skill_level must be one of {allowed}, got '{v}'")

    @field_validator("confidence", mode="before")
    @classmethod
    def validate_confidence(cls, v: str) -> str:
        allowed = ["Low", "Medium", "High"]
        for option in allowed:
            if option.lower() == v.strip().lower():
                return option
        raise ValueError(f"confidence must be one of {allowed}, got '{v}'")

    @field_validator("complexity_rating", mode="before")
    @classmethod
    def validate_complexity(cls, v: str) -> str:
        allowed = ["Low", "Medium", "High", "Very High"]
        for option in allowed:
            if option.lower() == v.strip().lower():
                return option
        v_lower = v.strip().lower()
        if "very" in v_lower and "high" in v_lower:
            return "Very High"
        if "high" in v_lower:
            return "High"
        if "medium" in v_lower or "moderate" in v_lower:
            return "Medium"
        if "low" in v_lower:
            return "Low"
        raise ValueError(f"complexity_rating must be one of {allowed}, got '{v}'")
